### ISSUE TITLE
Slaves not Opening trades when using 100% of balance

### ISSUE THREAD

**Issue by djcrawleravp** [MohammedRashad/Crypto-Copy-Trader#11]
Using Stop Limit with 100% balance

<img width="1920" alt="Stop limit100%" src="https://user-images.githubusercontent.com/12896341/82759086-db7a7380-9db8-11ea-8748-de2296a2571a.png">

Using buy Limit with 100% balance

<img width="1920" alt="Limit error 100%" src="https://user-images.githubusercontent.com/12896341/82759102-ffd65000-9db8-11ea-8115-85a211d08f7d.png">

**Comment by MohammedRashad** [comment]
what is 100% balance?

**Comment by djcrawleravp** [comment]
Hi Mohammed,

Its When the master account uses all of its funds to do a trade

**Comment by MohammedRashad** [comment]
Please pull the latest version, we fixed this bug.

Let me know if fixed.

**Comment by djcrawleravp** [comment]
I did a new pull yesterday,

I’ll try again later today


Thanks for the help!

**Comment by djcrawleravp** [comment]
I ran I new test, the issue still happening

**Comment by mokolotron** [comment]
I really found several bugs, one of them is that the system opens a order not from the entire available balance, but also from the blocked one (that is, which one is in orders). This will cause a "influenced of balance" error if you have other orders open.
     Also, an error can be detected by manipulations during the program's operation with the balance of those coins that are specified in config.csv in the first line.
     Now I am working on global refactoring and web sockets so I can fix these problems in the next pull-quest but it can take about a week

**Comment by MohammedRashad** [comment]
can you break them to smaller parts? like multiple pull requests so I can review and edit if needed?

**Comment by djcrawleravp** [comment]
Solved!
