### ISSUE TITLE
Parameter 'stopPrice' when placen an order

### ISSUE THREAD

**Issue by djcrawleravp** [MohammedRashad/Crypto-Copy-Trader#12]
Placing a 75% of the balance with Stop Limit

<img width="1920" alt="Stop limit 75%" src="https://user-images.githubusercontent.com/12896341/82759123-32804880-9db9-11ea-9028-16e10f4cb357.png">

**Comment by MohammedRashad** [comment]
will fix it within this week. thanks for informing me

**Comment by mokolotron** [comment]
This is not a critical error. Order will still be placed on slave accounts, despite the error. If not, let me know.

**Comment by djcrawleravp** [comment]
The order doesn’t place on my case using stop limit

**Comment by mokolotron** [comment]
1. Are the any other open orders on your account? 
2. What trade pair you use to create new order?

**Comment by djcrawleravp** [comment]
1. No other open orders on the account
2. All test were made with USDT/BTC
