### ISSUE TITLE
how to set the ratio for different slave accounts?

### ISSUE THREAD

**Issue by gzf445** [MohammedRashad/Crypto-Copy-Trader#25]
how to set the ratio for slave 1 or slave2 accounts?
for example,the main account invest 100 usd and the slave 1 1000 and slave2 50.
is it only support the same amount on the copy trade for the main accounts?

**Comment by mokolotron** [comment]
This feature is already enabled. When you create an order on the main account for $ 50, an order of about $ 500 will be created on the slave account 1, and the order will be created on the slave account 2 ~ 25 US dollars.

But be careful if you create small orders. For example, when you create a $ 10 order in the master account, the program will try to create a $ 5 order in the slave2 account, but the minimum order in the BTCUSDT trading pair is $ 10, so you will get an error and this may lead to other unexpected errors.

**Comment by gzf445** [comment]
> This feature is already enabled. When you create an order on the main account for $ 50, an order of about $ 500 will be created on the slave account 1, and the order will be created on the slave account 2 ~ 25 US dollars.
> 
> But be careful if you create small orders. For example, when you create a $ 10 order in the master account, the program will try to create a $ 5 order in the slave2 account, but the minimum order in the BTCUSDT trading pair is $ 10, so you will get an error and this may lead to other unexpected errors.

is it a auto setting base on the balance on different accounts?

**Comment by mokolotron** [comment]
Yes

**Comment by gzf445** [comment]
ok.thanks.
