### ISSUE TITLE
is there a log for the running?

### ISSUE THREAD

**Issue by gzf445** [MohammedRashad/Crypto-Copy-Trader#28]
hello.
i run the system for a day but it seems that it miss some trade on copied.
how can i find the log of the system ?

**Comment by mokolotron** [comment]
No. We haven't log in program now. Can you help us and add the logger?

**Comment by gzf445** [comment]
hello.i do not know how to add logger. nohup python api.py >> main.log 2>&1 &  may work. 
i use screen in linux to let it run background

**Comment by mokolotron** [comment]
Logger added. The log is located in the `logs/cct.log`
