### ISSUE TITLE
the free balance not update after the first copy trade.

### ISSUE THREAD

**Issue by gzf445** [MohammedRashad/Crypto-Copy-Trader#29]
\Slave {'asset': 'USDT', 'free': '130.741099060', 'locked': '0.00000000'} {'asset': 'BTC', 'free': '0.00000000', 'locked': '0.00000000'}, Create Order: amount: 0.004525, price: 11787.47000000
order created
Slave {'asset': 'USDT', 'free': '137.741715760', 'locked': '0.00000000'} {'asset': 'BTC', 'free': '0.00000000', 'locked': '0.00000000'}, Create Order: amount: 0.004767, price: 11787.47000000
\order created

this is the first copy trade,
and the second
Slave {'asset': 'USDT', 'free': '130.741099060', 'locked': '0.00000000'} {'asset': 'ETH', 'free': '0.05712000', 'locked': '0.00000000'}, Create Order: amount: 0.27874, price: 397.23000000
APIError(code=-2010): Account has insufficient balance for requested action.
Slave {'asset': 'USDT', 'free': '81.551036950', 'locked': '0.00000000'} {'asset': 'ETH', 'free': '0.05712000', 'locked': '0.00000000'}, Create Order: amount: 0.17387, price: 397.23000000
order created

actualy the first slave just have about 80 free usdt after the first copy.
it seems the balance not update after the first trade.

**Comment by mokolotron** [comment]
Sorry for the long absence. I didn't have time to support the project.
When Pullrequest is accepted the bug will be fixed.
But you will need to switch and update to develop branch

**Comment by MohammedRashad** [comment]
Pull request merged
