### ISSUE TITLE
Remove Single Slave Account 

### ISSUE THREAD

**Issue by codemasterlike** [MohammedRashad/Crypto-Copy-Trader#38]
Dear,
When I click the delete/remove button on Slave Account on browser http://0.0.0.0:5000, it delete/remove all Slave accounts. Do we have option to remove single account only or how to manually do it, please?

Thanks very much.

**Comment by mokolotron** [comment]
Hello. Currently delete/add actions  is not working for accounts. You must add or delete master and slaves in file `./config_files/config.json`
If you dont have this file then copy file `./config_files/config-sample.json` and rename it to `config.json`
( ` cp ./config_files/config-sample.json ./config_files/config.json ` )

**Comment by codemasterlike** [comment]
Thanks mokolotron
