### ISSUE TITLE
Question:  Maximum number of slaves

### ISSUE THREAD

**Issue by alexandrebouttier** [MohammedRashad/Crypto-Copy-Trader#40]
Hello, I have a quick question, what is the number of slaves possible on the same master, how does it manage this in relation to the binance restrictions? Thank you for your work by the way

**Comment by mokolotron** [comment]
Hello. There are no restrictions directly in the program, so the number of subordinates can be quite large.
But care must be taken to ensure that the request rate is not exceeded in accordance with the exchange restrictions.
- The program uses web sockets to receive information about the order and update the balance.
- But to send an order, the program uses a rest request.
- And another rest request is sent when a market order is received, to get the current price of the symbol.

You can check the binance API frequency limit at the link: https://binance-docs.github.io/apidocs/spot/en/#limits
