### ISSUE TITLE
QUESTION frontend React  & Evolution 

### ISSUE THREAD

**Issue by alexandrebouttier** [MohammedRashad/Crypto-Copy-Trader#47]
Hello, I use your copybot which works very well thank you, for my part I transform the interface into React in the form of a dashboard, I wonder if you would be interested that once my work is finished to share with you in order to contribute to your project, the dashboard will be able to add new slaves with a mongoDB database, be able to add an allocation option in the slaves to dedicate an allocated sum in percentage, encryption of API secret keys, exchange choice, jwt connection to protect the table on board, recording each order of each slave, start shutting down the bot, and then see the stats of the bot

**Comment by mokolotron** [comment]
Hello. I glad to read that its tool was useful to you.
I would appreciate any help on the project. Your plan sounds good.
If you have any question or help with written code let me know. 
Also do not be afraid to improve or radically change already written code.

**Comment by alexandrebouttier** [comment]
> Hello. I glad to read that this tool is useful to you.
> I would appreciate any help on the project. Your plan sounds good.
> If you have any question or help with written code let me know.
> Also do not be afraid to improve or radically change already written code.

Ok very well, I will let you know when the front end is finished for my part, I only touch the front-end, it is more my domain
