### ISSUE TITLE
Bitmex pair problem.

### ISSUE THREAD

**Issue by allhq** [MohammedRashad/Crypto-Copy-Trader#54]
Hi! I install ubuntu 20. 
Use BItmex, edit symbols.csv -> XBTUSD  ETHUSD 
Cant start the bot. 

mezo@mezo:~/Crypto-Copy-Trader$ python3 api.py
 * Serving Flask app "api" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: on
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 282-647-152
192.168.1.89 - - [24/Feb/2021 14:37:37] "GET / HTTP/1.1" 200 -
2021-02-24 14:37:38,587 - INFO - The Crypto-Copy-Trader starts launch
2021-02-24 14:37:38,588 - INFO - Reading configuration file...
2021-02-24 14:37:38,588 - INFO - 2 Slave accounts detected
2021-02-24 14:37:38,588 - INFO - Connecting to the master: Master...
2021-02-24 14:37:38,589 - DEBUG - Can't translate word ETHUSD  in Bitmex
/home/mezo/.local/lib/python3.8/site-packages/swagger_spec_validator/validator20.py:49: SwaggerValidationWarning: Found "$ref: #/definitions/UserPreferences" with siblings that will be overwritten. See https://stackoverflow.com/a/48114924 for more information. (path #/definitions/User/properties/preferences)
  warnings.warn(

Many thanx \o/

**Comment by mokolotron** [comment]
Try to replace XBTUSD to BTCUSDT, and ETHUSD to ETHUSDT in symbols.csv

**Comment by allhq** [comment]
Thx working
