### ISSUE TITLE
Binance Futures Support

### ISSUE THREAD

**Issue by edisonta456** [MohammedRashad/Crypto-Copy-Trader#58]
Hello, I've tried to add Binance futures support to this and have changed all the methods required to communicate with the new exchange. It is able to copy existing orders successfully, but I'm not sure why the websocket is not picking up any user stream data? It says the websocket is launched but no events are picked up.
I've checked the websocket separately and it is able to pick up events but not when I try to implement it into here.

**Comment by illiagerega** [comment]
Hello. Could you share or send me somewhere the code, which support binance futures?
