### ISSUE TITLE
Crash at starting the bot

### ISSUE THREAD

**Issue by djcrawleravp** [MohammedRashad/Crypto-Copy-Trader#8]
Any ideas?

Api Keys were copy pasted

<img width="1541" alt="Screen Shot 2020-04-10 at 13 39 24" src="https://user-images.githubusercontent.com/12896341/79010847-c8755200-7b30-11ea-882c-39ea8f2e561c.png">

**Comment by MohammedRashad** [comment]
how are you pasting them inside the csv?

**Comment by djcrawleravp** [comment]
I have tried both ways, either the csv and the web interface

**Comment by MohammedRashad** [comment]
can you please try python3 ?

**Comment by djcrawleravp** [comment]
Nothing happens

**Comment by djcrawleravp** [comment]
<img width="900" alt="Screen Shot 2020-04-12 at 11 46 55" src="https://user-images.githubusercontent.com/12896341/79235033-1512a300-7e39-11ea-9d5f-dddcab1e105e.png">

**Comment by djcrawleravp** [comment]
Same thing using python3 :/

**Comment by djcrawleravp** [comment]
Digging up a little, i found that it detects 3 slave accounts but I'm just testing 1 master and 1 slave
<img width="440" alt="Screen Shot 2020-04-16 at 16 23 52" src="https://user-images.githubusercontent.com/12896341/79503232-cb73b500-7ffe-11ea-8df5-741f6de4166e.png">

**Comment by djcrawleravp** [comment]
Digging up a little I found that It's detecting 3 Slaves?

I'm just testing with 1 master and 1 slave
<img width="440" alt="Screen Shot 2020-04-16 at 16 23 52" src="https://user-images.githubusercontent.com/12896341/79503304-ee9e6480-7ffe-11ea-8a03-42835fdf32c8.png">

**Comment by djcrawleravp** [comment]
Well this is ODD

I figured it out but I'm not sure if is correct...

The console was showing that found 3 slave APIs (but I'm just using one)

So I put my API keys twice (image attached) and It appears to be working

Is that correct?
<img width="285" alt="Screen Shot 2020-04-16 at 16 29 04" src="https://user-images.githubusercontent.com/12896341/79503708-9d42a500-7fff-11ea-8cc7-e8678cd1a60f.png">
<img width="633" alt="Screen Shot 2020-04-16 at 16 30 32" src="https://user-images.githubusercontent.com/12896341/79503724-a5024980-7fff-11ea-9495-ba3e59993c52.png">

**Comment by MohammedRashad** [comment]
yes this is correct

**Comment by djcrawleravp** [comment]
Minimun 2 Slaves then!, Great!!

Thanks!
