### ISSUE TITLE
Using % of the Master Balance

### ISSUE THREAD

**Issue by djcrawleravp** [MohammedRashad/Crypto-Copy-Trader#9]
Is it possible to modify the order amount in order for every account use the same percentage as the master?

**Example:**

**Master has 10 BTC** and opens a new buy limit of **5BTC** at **6500USD** (50% of the balance)

**Slave 1 has 14 BTC**, the script opens a new buy limit of **7BTC** at **6500USD** (50% of the balance)

**Slave 2 has 3 BTC**, the script opens a new buy limit of **1.5BTC** at **6500USD** (50% of the balance)

Maybe changing the value **"quantity=order['origQty']"** adding the formula for the original percentage?

Thanks for the patience, I'm not very much experienced in developing.

**Comment by MohammedRashad** [comment]
I was working on this feature and stopped due to other priorities, can you help with it?

**Comment by djcrawleravp** [comment]
I’m not a developer but i can try

**Comment by mokolotron** [comment]
Is the problem still relevant? Maybe I can help.

**Comment by djcrawleravp** [comment]
I’m still looking for a solution, :/

**Comment by MohammedRashad** [comment]
@mokolotron I have no time to maintain this project now, can you help in this feature?

**Comment by mokolotron** [comment]
I can try it.

**Comment by MohammedRashad** [comment]
thank you. waiting for your update

**Comment by MohammedRashad** [comment]
Update Merged, please test the feature and let me know what do you think
